### ISSUE TITLE
Field Extension Support in Lists with termSuffix

### ISSUE THREAD

**Issue by KhaledEmaraDev** [commschamp/commsdsl#19]
I have the following protocol definition:

```
<bundle name="DataItem100" displayName="Processing Status" description="Information concerning the scaling factor currently applied, current reduction step in use, etc.">
    <bitfield name="B24_1">
        <set name="FX" bitLength="1">
            <bit name="fx" displayName="Field extension" idx="0" />
        </set>
        <int name="Q" displayName="Processing parameters" type="uint16" bitLength="15" />
        <enum name="R" displayName="Current reduction stage" type="uint8" bitLength="3">
            <validValue name="NormalOperation" displayName="Normal operation" val="0" />
        </enum>
        <int name="f" displayName="Scaling factor f" type="uint8" bitLength="5" />
    </bitfield>
</bundle>
```

This bundle can be repeated until the fx field is set to 0. I think this is a common occurrence in many protocols.

I would love it if either of the two following solutions is possible:
1: `temSuffix` for `list` is bit wise not byte wise.
2: `list`s support `cond` like `optional`.

**Comment by arobenko** [comment]
Maybe I don't understand exactly what you mean, but I think usage of the `<termSuffix>` is sufficient in your case. Something like:
```
<list name="MyList" element="DataItem100>
    <termSuffix>
        <int name="Term" type="uint8" defaultValidValue="0" failOnInvalid="true" />
    </termSuffix>
</list>
```
Unless zeroed FX bit indicates the last element in the list. In such case you need to write your custom `read`,  functions which read elements one by one, checks the FX bit after each iteration and terminates the loop if necessary. Maybe some other functions (like `refresh` which sets the FX bit in all the list elements accordingly) also need to be implemented.

If I'm wrong, please clarify exactly what you need and why existing methods are insufficient.

**Comment by KhaledEmaraDev** [comment]
@arobenko `fx` indicates whether there is another `element` in the `list` or not. 

My problem is that I believe `termSuffix` to need the entire byte to be zero in order to terminate the list.
This is not the case in the protocol I'm implementing. Only the last bit determines this. So it maybe `0b00000000` or `0b00000010` or any other form that ends with the last bit = 0.

I think it might be doable with custom code as you mentioned. I was thinking that having `cond` on `lists` to implement the condition on which the loop should exit would be an easier way.

**Comment by arobenko** [comment]
Hi @KhaledEmaraDev,
The COMMS library implements the logic behind the `<termSuffix>` in the following way:

- Attempt to read the termination suffix field. If it's successful, the read operation successfully terminates.
- If the read operation of the termination suffix fails, then attempt to read list element from the same place.
- Repeat the operations above until the list is terminated or error on element read occurs.

It means that you need to define your `<termSuffix>` in a way that fails if LSB is 1, and successful if it is 0. I think using the `<set>` (with LSB defined as reserved) instead of `<int>` as your termination suffix will do the job:
```
<termSuffix>
    <set name="Term" length="1" failOnInvalid="true">
        <!-- skip mention of first bit make it reserved -->
        <bit name="B1" idx="1" />
        <bit name="B2" idx="2" />
        <bit name="B3" idx="3" />
        <bit name="B4" idx="4" />
        <bit name="B5" idx="5" />
        <bit name="B6" idx="6" />
        <bit name="B7" idx="7" />
    </set>
</termSuffix>
```
Usage of the **failOnInvalid** property makes sure that the read operation fails when the reserved bit is set, as the result allowing your list to continue with the element read operation.

If you need to access the termination field's value after the read operation takes place you can use newly introduced (available on develop branch) [terminationSuffixField()](https://github.com/commschamp/comms/blob/develop/include/comms/field/ArrayList.h#L589) member function of the list field.

**Comment by KhaledEmaraDev** [comment]
Thank you so much @arobenko again for the prompt response. This more than solves my problem.
