### ISSUE TITLE
Can a (serial) protocol with character escaping be realized using the custom code feature?

### ISSUE THREAD

**Issue by TimonTerBraak** [commschamp/commsdsl#23]
I have a character-based protocol with a STX and ETX character, and where the payload is escaped with an escape character. I have a working protocol encoder/decoder using commsdsl. But I have not been able to do the frame reading/writing using this framework.

As a workaround I have the following:

`    <frame name="ProtocolFrame">
        <layers>
            
            <id name="cmd" field="cmd"/>
            <payload name="Data"/>
            <checksum name="CRC" alg="custom" algName="CRC8DallasMaxim" from="uC">
                <int name="CRCField" type="uint8"/>
            </checksum>
            
        </layers>
    </frame>`

In my own C++ code I do the (un)escaping, and the STX/ETX handling before and after the commsdsl frame handling. Works fine, but I would like to know the framework better to see if I can improve on this.
So, can I customize the frame reading/writing to peform the character escaping before and after the frame encoding and decoding?

**Comment by arobenko** [comment]
Hi @TimonTerBraak,
There are no built-in means to easily handle protocols like yours in the CommsChampion Ecosystem. I think performance wise it's better for you to pre- and post-process the payload by removing / adding escape characters, just like you do now. Such code is quite simple both to write and quick compile.

However, it is possible to implement such pre- and post-processing using the means of the CommsChampion Ecosystem, but it will take more effort to implement it and due to usage of the templates the compilation will take longer. The implementation will require splitting your protocol into two separate ones, one to handle the framing and escaping, and the second one to handle a payload to determine actual messages. So, it will still require two passes on the data anyway. With the currently available feature set you will probably have to use [custom code injection](https://github.com/commschamp/commsdsl/blob/master/doc/Manual_commsdsl2comms.md#custom-code). Maybe in the future I will implement extra features to the CommsDSL spec,  commsdsl code generates, and COMMS library which will eliminate the necessity to inject custom code for such case, bit it won't happen within the next couple of months and it won't eliminate two passes on the data.

Please let me know if you want me to advice on the details on how to implement such two passes using the CommsChampion Ecosystem.

**Comment by TimonTerBraak** [comment]
Thanks for the quick feedback. Then I'll stick to my current implementation. The advantage of doing this in the COMMS part is the decoupling of the application logic, improving the reusability of this functionality for other protocol.
